# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attempts', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbs.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('activity', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('achievements', models.ManyToManyField(to='climbs.Route')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbs.Location')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbs.Location'),
        ),
    ]
